"use client";

import { useCallback, useEffect, useState } from "react";
import { ErrorState, LoadingState, Panel } from "@/components/ui/states";
import { ApiError, getExplanation, requestExplanation } from "@/lib/api/client";
import type { MatchExplanation } from "@/lib/api/client";

/**
 * The written explanation for one ranked job.
 *
 * The strengths, gaps and evidence come from the application's own comparison,
 * so they are shown even when generation is unavailable. An unavailable
 * explanation is labelled as such: a missing generated paragraph is never
 * presented as a finished answer.
 */
export function ExplanationPanel({
  candidateId,
  revision,
  jobId,
}: {
  candidateId: string;
  revision: number;
  jobId: string;
}) {
  const [explanation, setExplanation] = useState<MatchExplanation | null>(null);
  const [error, setError] = useState<ApiError | null>(null);
  const [loading, setLoading] = useState(true);

  const generate = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setExplanation(await requestExplanation(candidateId, revision, jobId));
    } catch (caught) {
      setError(
        caught instanceof ApiError
          ? caught
          : new ApiError(0, "UNEXPECTED_ERROR", "The request failed.", false),
      );
    } finally {
      setLoading(false);
    }
  }, [candidateId, revision, jobId]);

  useEffect(() => {
    let active = true;
    getExplanation(candidateId, revision, jobId)
      .then((value) => {
        if (!active) return;
        setExplanation(value);
        setLoading(false);
        if (value.state === "pending") void generate();
      })
      .catch((caught: unknown) => {
        if (!active) return;
        setError(
          caught instanceof ApiError
            ? caught
            : new ApiError(0, "UNEXPECTED_ERROR", "The request failed.", false),
        );
        setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [candidateId, revision, jobId, generate]);

  if (loading && !explanation) return <LoadingState label="Preparing the explanation…" />;
  if (error && !explanation) {
    return (
      <ErrorState
        title="The explanation could not be loaded"
        detail={error.message}
        onRetry={() => void generate()}
      />
    );
  }
  if (!explanation) return null;

  return (
    <Panel>
      <h2 className="font-medium">Why this job was ranked</h2>
      {explanation.state === "ready" && explanation.text ? (
        <p className="mt-2 text-sm leading-6">{explanation.text}</p>
      ) : (
        <p className="mt-2 text-sm leading-6 text-emerald-950/70">
          {explanation.state === "pending"
            ? "The written explanation is still being generated. The comparison below is already final."
            : "The written explanation is unavailable right now. The comparison below comes from your resume and the posting, not from a language model."}
        </p>
      )}
      {explanation.strengths.length > 0 ? (
        <>
          <h3 className="mt-4 text-sm font-medium">Strengths</h3>
          <ul className="mt-1 list-disc pl-5 text-sm leading-6">
            {explanation.strengths.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </>
      ) : null}
      {explanation.gaps.length > 0 ? (
        <>
          <h3 className="mt-4 text-sm font-medium">Not evidenced in your resume</h3>
          <ul className="mt-1 list-disc pl-5 text-sm leading-6">
            {explanation.gaps.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </>
      ) : null}
      {explanation.state === "ready" && explanation.model_version ? (
        <p className="mt-4 text-xs text-emerald-950/55">
          Generated by {explanation.model_version} using prompt {explanation.prompt_version}, from
          the quoted resume and posting text only.
        </p>
      ) : null}
    </Panel>
  );
}
