"""Initial career_app schema: sessions and candidate retention, resume upload
metadata, versioned profiles and embeddings, analysis runs, the durable work
queue with its processed-event record and match runs, pair scores, published
recommendation revisions and cached explanations. Owner: M3 (C-01).

Independent of the career_jobs chain: no table here references a job table, and
no migration in either chain may depend on the other."""

import sqlalchemy as sa
from alembic import op

revision = "0001_app_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("current_profile_version", sa.Integer(), nullable=True),
        sa.Column("matching_enabled", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index(
        "ix_candidates_active", "candidates", ["matching_enabled", "expires_at"], unique=False
    )
    op.create_table(
        "explanations",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("model_version", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("candidate_id", "revision", "job_id"),
    )
    op.create_table(
        "match_results",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=200), nullable=False),
        sa.Column("job_version", sa.Integer(), nullable=False),
        sa.Column("scoring_version", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "candidate_id", "profile_version", "job_id", "job_version", "scoring_version"
        ),
    )
    op.create_index(
        "ix_match_results_ranking",
        "match_results",
        ["candidate_id", "profile_version"],
        unique=False,
    )
    op.create_table(
        "match_runs",
        sa.Column("run_id", sa.String(length=200), nullable=False),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("event", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("checkpoint", sa.Text(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("published_revisions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "recommendation_revisions",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("refresh_state", sa.String(length=20), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("candidate_id", "revision"),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=200), nullable=False),
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
        sa.UniqueConstraint("candidate_id"),
    )
    op.create_table(
        "work_queue",
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("queue", sa.String(length=30), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_work_queue_claim", "work_queue", ["queue", "state", "available_at"], unique=False
    )
    op.create_table(
        "analysis_runs",
        sa.Column("analysis_id", sa.String(length=200), nullable=False),
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("resume_id", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("corpus_snapshot", sa.Text(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("analysis_id"),
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id", "profile_version"),
    )
    op.create_table(
        "recommendation_entries",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=200), nullable=False),
        sa.Column("job_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id", "revision"],
            ["recommendation_revisions.candidate_id", "recommendation_revisions.revision"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("candidate_id", "revision", "rank"),
    )
    op.create_table(
        "resume_uploads",
        sa.Column("resume_id", sa.String(length=200), nullable=False),
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("resume_id"),
    )
    op.create_table(
        "candidate_embeddings",
        sa.Column("candidate_id", sa.String(length=200), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("embedding_version", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("model_revision", sa.Text(), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("preprocessing_version", sa.Text(), nullable=False),
        sa.Column("vector", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id", "profile_version"],
            ["candidate_profiles.candidate_id", "candidate_profiles.profile_version"],
        ),
        sa.PrimaryKeyConstraint("candidate_id", "profile_version", "embedding_version"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidate_embeddings")
    op.drop_table("resume_uploads")
    op.drop_table("recommendation_entries")
    op.drop_table("candidate_profiles")
    op.drop_table("analysis_runs")
    op.drop_index("ix_work_queue_claim", table_name="work_queue")
    op.drop_table("work_queue")
    op.drop_table("sessions")
    op.drop_table("recommendation_revisions")
    op.drop_table("processed_events")
    op.drop_table("match_runs")
    op.drop_index("ix_match_results_ranking", table_name="match_results")
    op.drop_table("match_results")
    op.drop_table("explanations")
    op.drop_index("ix_candidates_active", table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
